/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PosRouteImport } from './routes/pos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryAdjustmentRouteImport } from './routes/inventory.adjustment'
import { Route as InventoryCountRouteImport } from './routes/inventory.count'
import { Route as InventoryMovementsRouteImport } from './routes/inventory.movements'
import { Route as InventoryStockInRouteImport } from './routes/inventory.stock-in'
import { Route as InventoryStockOutRouteImport } from './routes/inventory.stock-out'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PromotionsIndexRouteImport } from './routes/promotions.index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesOrderIdRouteImport } from './routes/sales.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAdjustmentRoute = InventoryAdjustmentRouteImport.update({
  id: '/inventory/adjustment',
  path: '/inventory/adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryCountRoute = InventoryCountRouteImport.update({
  id: '/inventory/count',
  path: '/inventory/count',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryMovementsRoute = InventoryMovementsRouteImport.update({
  id: '/inventory/movements',
  path: '/inventory/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStockInRoute = InventoryStockInRouteImport.update({
  id: '/inventory/stock-in',
  path: '/inventory/stock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStockOutRoute = InventoryStockOutRouteImport.update({
  id: '/inventory/stock-out',
  path: '/inventory/stock-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsIndexRoute = PromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrderIdRoute = SalesOrderIdRouteImport.update({
  id: '/sales/$orderId',
  path: '/sales/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/settings': typeof SettingsRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/count': typeof InventoryCountRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/stock-in': typeof InventoryStockInRoute
  '/inventory/stock-out': typeof InventoryStockOutRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/sales/$orderId': typeof SalesOrderIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/settings': typeof SettingsRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/count': typeof InventoryCountRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/stock-in': typeof InventoryStockInRoute
  '/inventory/stock-out': typeof InventoryStockOutRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/sales/$orderId': typeof SalesOrderIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/products': typeof ProductsIndexRoute
  '/promotions': typeof PromotionsIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/settings': typeof SettingsRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/count': typeof InventoryCountRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/stock-in': typeof InventoryStockInRoute
  '/inventory/stock-out': typeof InventoryStockOutRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/sales/$orderId': typeof SalesOrderIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/login'
    | '/pos'
    | '/settings'
    | '/inventory/adjustment'
    | '/inventory/count'
    | '/inventory/movements'
    | '/inventory/stock-in'
    | '/inventory/stock-out'
    | '/products/$productId'
    | '/sales/$orderId'
    | '/inventory/'
    | '/products/'
    | '/promotions/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/login'
    | '/pos'
    | '/settings'
    | '/inventory/adjustment'
    | '/inventory/count'
    | '/inventory/movements'
    | '/inventory/stock-in'
    | '/inventory/stock-out'
    | '/products/$productId'
    | '/sales/$orderId'
    | '/inventory'
    | '/products'
    | '/promotions'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/login'
    | '/pos'
    | '/settings'
    | '/inventory/adjustment'
    | '/inventory/count'
    | '/inventory/movements'
    | '/inventory/stock-in'
    | '/inventory/stock-out'
    | '/products/$productId'
    | '/sales/$orderId'
    | '/inventory/'
    | '/products/'
    | '/promotions/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  SettingsRoute: typeof SettingsRoute
  InventoryAdjustmentRoute: typeof InventoryAdjustmentRoute
  InventoryCountRoute: typeof InventoryCountRoute
  InventoryMovementsRoute: typeof InventoryMovementsRoute
  InventoryStockInRoute: typeof InventoryStockInRoute
  InventoryStockOutRoute: typeof InventoryStockOutRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  SalesOrderIdRoute: typeof SalesOrderIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PromotionsIndexRoute: typeof PromotionsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/adjustment': {
      id: '/inventory/adjustment'
      path: '/inventory/adjustment'
      fullPath: '/inventory/adjustment'
      preLoaderRoute: typeof InventoryAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/count': {
      id: '/inventory/count'
      path: '/inventory/count'
      fullPath: '/inventory/count'
      preLoaderRoute: typeof InventoryCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/movements': {
      id: '/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof InventoryMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stock-in': {
      id: '/inventory/stock-in'
      path: '/inventory/stock-in'
      fullPath: '/inventory/stock-in'
      preLoaderRoute: typeof InventoryStockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stock-out': {
      id: '/inventory/stock-out'
      path: '/inventory/stock-out'
      fullPath: '/inventory/stock-out'
      preLoaderRoute: typeof InventoryStockOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions/': {
      id: '/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof PromotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$orderId': {
      id: '/sales/$orderId'
      path: '/sales/$orderId'
      fullPath: '/sales/$orderId'
      preLoaderRoute: typeof SalesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  SettingsRoute: SettingsRoute,
  InventoryAdjustmentRoute: InventoryAdjustmentRoute,
  InventoryCountRoute: InventoryCountRoute,
  InventoryMovementsRoute: InventoryMovementsRoute,
  InventoryStockInRoute: InventoryStockInRoute,
  InventoryStockOutRoute: InventoryStockOutRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  SalesOrderIdRoute: SalesOrderIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PromotionsIndexRoute: PromotionsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
